name: Build Local Dream

on:
  workflow_dispatch:

env:
  APP_NAME: "LocalDream"
  FOLDER_NAME: "build"
  ANDROID_NDK_VERSION: "r28"
  QNN_SDK_VERSION: "2.29.0.241129"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build unzip curl build-essential git
          rustup update stable
          rustup default stable
          rustup target add aarch64-linux-android

      - name: Download and setup Android NDK
        run: |
          curl -L https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip -o ndk.zip
          unzip -q ndk.zip -d $HOME
          echo "ANDROID_NDK_ROOT=$HOME/android-ndk-${ANDROID_NDK_VERSION}" >> $GITHUB_ENV

      - name: Download and setup QNN SDK
        run: |
          curl -L https://apigwx-aws.qualcomm.com/qsc/public/v1/api/download/software/qualcomm_neural_processing_sdk/v${QNN_SDK_VERSION}.zip -o qnn.zip
          unzip -q qnn.zip -d $HOME
          SDK_DIR=$(find $HOME -maxdepth 1 -type d -name "qualcomm_neural_processing_sdk*")
          echo "QNN_SDK_ROOT=$SDK_DIR" >> $GITHUB_ENV

      - name: Build native libraries
        run: |
          cd app/src/main/cpp
          bash ./build.sh

      - name: Build APK with Gradle
        run: |
          ./gradlew assembleRelease

      - name: Create folder for release
        run: mkdir -p ${{ env.FOLDER_NAME }}

      - name: Copy APK to release folder
        run: cp app/build/outputs/apk/release/app-release.apk ${{ env.FOLDER_NAME }}/${{ env.APP_NAME }}.apk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-artifacts
          path: ${{ env.FOLDER_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: ${{ env.APP_NAME }} Build ${{ github.run_number }}
          draft: false
          prerelease: false
          files: ${{ env.FOLDER_NAME }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
