name: Build and Release

on:
  workflow_dispatch:

env:
  APP_NAME: "MyApp"
  FOLDER_NAME: "apks/magisk/custom_font_installer"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          echo "RELEASE_NAME=${{ env.APP_NAME }} Release" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create folders
        run: mkdir -p ${{ env.FOLDER_NAME }}

      - name: Download APK
        run: |
          curl -L -o ${{ env.FOLDER_NAME }}/${{ env.APP_NAME }}.apk "https://example.com/path/to/app.apk"

      - name: Download Image
        run: |
          curl -L -o ${{ env.FOLDER_NAME }}/screenshot.png "https://example.com/path/to/screenshot.png"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-artifacts
          path: ${{ env.FOLDER_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          files: ${{ env.FOLDER_NAME }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
