name: Build Local Dream

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake unzip

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip -d $HOME
          echo "ANDROID_NDK_ROOT=$HOME/android-ndk-r26d" >> $GITHUB_ENV

      - name: Download QNN SDK
        run: |
          wget https://apigwx-aws.qualcomm.com/qsc/public/v1/api/download/software/qualcomm_neural_processing_sdk/v2.29.0.241129.zip -O qnn.zip
          unzip qnn.zip -d $HOME
          echo "QNN_SDK_ROOT=$HOME/qualcomm_neural_processing_sdk" >> $GITHUB_ENV

      - name: Build native libs
        run: |
          cd app/src/main/cpp
          bash ./build.sh

      - name: Build APK
        run: |
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LocalDream-APK
          path: app/build/outputs/apk/release/*.apk
          
